name: nadron
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Your Name <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  json_object: any

dev_dependencies:
  test: ^0.12.0

transformers:
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]